const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Behaviors.Tween,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.bound,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Plugins.Particles,
		C3.Plugins.NinePatch,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.SetBoolVar
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Browser: 0},
	{Mouse: 0},
	{Audio: 0},
	{URL: 0},
	{CreditsText: 0},
	{Column: 0},
	{Row: 0},
	{Flash: 0},
	{Tween: 0},
	{MagneticBlock: 0},
	{Brick: 0},
	{Color: 0},
	{DragDrop: 0},
	{BoundToLayout: 0},
	{Fade: 0},
	{Magnet: 0},
	{Position: 0},
	{DropZone: 0},
	{TiledBackground: 0},
	{Particles: 0},
	{RestartButton: 0},
	{InfoText: 0},
	{InfoTextBackground: 0},
	{Grid: 0},
	{CheckboxName: 0},
	{Checkbox: 0},
	{PlayGameButton: 0},
	{Title: 0},
	{MenuButton: 0},
	{MagnetsMotif: 0},
	{GRID_SIZE: 0},
	{NUMBER_OF_COLUMNS: 0},
	{NUMBER_OF_ROWS: 0},
	{DnDPickupX: 0},
	{DnDPickupY: 0},
	{GRID_TOP_POSITION: 0},
	{GRID_LEFT_POSITION: 0},
	{IsMusicOn: 0},
	{IsSFXOn: 0},
	{IsColorBlindModeOn: 0},
	{MagnetAngle: 0},
	{InitialColumn: 0},
	{InitialRow: 0},
	{NewColumn: 0},
	{NewRow: 0},
	{BlockColor: 0},
	{BlockUID: 0},
	{MagnetColor: 0},
	{Wait: 0},
	{MagnetAnimation: 0},
	{MagnetX: 0},
	{MagnetY: 0},
	{LastLayout: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	CreditsText: class extends self.ITextInstance {},
	MagneticBlock: class extends self.ISpriteInstance {},
	Brick: class extends self.ISpriteInstance {},
	Magnet: class extends self.ISpriteInstance {},
	DropZone: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Particles: class extends self.IParticlesInstance {},
	RestartButton: class extends self.ISpriteInstance {},
	InfoText: class extends self.ITextInstance {},
	InfoTextBackground: class extends self.ITiledBackgroundInstance {},
	Grid: class extends self.ISpriteInstance {},
	Checkbox: class extends self.ISpriteInstance {},
	PlayGameButton: class extends self.IWorldInstance {},
	Title: class extends self.ISpriteInstance {},
	MenuButton: class extends self.ISpriteInstance {},
	MagnetsMotif: class extends self.ITiledBackgroundInstance {}
}